network_parameters:
  attention_dim: 256
  encoder_dim: 2048
  decoder_dim: 512
  embed_size: 300
  drop_rate: 0.3

training_parameters:
  batch_size: 128
  num_workers: 0
  num_epoch: 2
  learning_rate: 0.0003

data_locations:
  img_dir: '../data/Images/'
  caption_dir: '../data/captions.txt'